### ISSUE TITLE
mobile display left edge

### ISSUE THREAD

**Issue by Maggi68** [bpextensions/mod_bpslider#28]
Hello,
I tried the modul and at mobile responsive view the text and background is set to left edge.
See https://j4.gfg-fortbildung.de/index.php
I set it to center, is it a problem with the template (Cassiopeia/ Child of Phoca cart) or maybe the modul?
THX

**Comment by artur-stepien** [comment]
> Hello, I tried the modul and at mobile responsive view the text and background is set to left edge. See https://j4.gfg-fortbildung.de/index.php I set it to center, is it a problem with the template (Cassiopeia/ Child of Phoca cart) or maybe the modul? THX

Hello. It looks like a module issue (at least I think it is). I'll check it out and release a proper fix or let you know what caused it.

**Comment by Maggi68** [comment]
OK thx.....

**Comment by Maggi68** [comment]
Hello,
i want to ask about the check and fix above, or take it time....?
Regards

**Comment by artur-stepien** [comment]
New version fixing the issue should be available for update.
